"""LLM-driven test state generation for COBOL coverage.

Uses a 3-agent pipeline to build a compact, high-signal prompt:
  1. Comments Agent (deterministic) — extracts business-logic comments from
     COBOL source between paragraph boundaries.
  2. Flow Agent (deterministic) — summarises call graph, stub operations,
     gating conditions, and branch structure from the AST.
  3. Synthesis Agent (LLM) — receives the compact context and queries the
     LLM for test states.

Designed to seed cobol_coverage.py Layer 0 with high-quality initial states
that target stub-dependent branches (CICS DFHRESP, IMS DLI status, file
status codes) which heuristic generation cannot reach.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

from .llm_coverage import _query_llm_sync
from .models import Program, Paragraph, Statement
from .static_analysis import StaticCallGraph, GatingCondition
from .variable_domain import VariableDomain
from .variable_extractor import VariableReport

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class LLMTestState:
    """A complete test state generated by the LLM."""

    input_values: dict[str, str] = field(default_factory=dict)
    stub_overrides: dict[str, str] = field(default_factory=dict)
    target_description: str = ""
    reasoning: str = ""


# ---------------------------------------------------------------------------
# Agent 1: Comments Agent (deterministic)
# ---------------------------------------------------------------------------

_DECORATIVE_RE = re.compile(r'^[\s*=\-/\\#+]+$')
_BOILERPLATE_KW = frozenset({
    "copyright", "license", "licensed", "all rights reserved",
    "modification log", "change log", "change history",
    "author:", "date:", "written by",
})


def extract_paragraph_comments(
    program: Program,
    source_lines: list[str],
) -> dict[str, list[str]]:
    """Extract condensed comment bullets for each paragraph.

    Looks at COBOL comment lines in the zone between the previous
    paragraph's end and the current paragraph's start.
    """
    if not program.paragraphs or not source_lines:
        return {}

    sorted_paras = sorted(program.paragraphs, key=lambda p: p.line_start)
    result: dict[str, list[str]] = {}

    for idx, para in enumerate(sorted_paras):
        # Comment zone: from previous paragraph end (or line 0) to this start
        if idx == 0:
            zone_start = 0
        else:
            zone_start = sorted_paras[idx - 1].line_end  # 1-based end → 0-based next

        zone_end = para.line_start - 1  # 1-based start → 0-based line before

        if zone_end <= zone_start:
            continue

        raw_comments = _collect_comment_lines(source_lines, zone_start, zone_end)
        bullets = _compact_comments(raw_comments)
        if bullets:
            result[para.name] = bullets

    return result


def _collect_comment_lines(
    source_lines: list[str],
    zone_start: int,
    zone_end: int,
) -> list[str]:
    """Collect comment text from source lines in the given 0-based range."""
    comments: list[str] = []

    for i in range(zone_start, min(zone_end, len(source_lines))):
        line = source_lines[i]

        # Fixed-format: column 7 (index 6) is '*' → rest is comment
        if len(line) > 6 and line[6] == '*':
            text = line[7:].strip()
            if text and line[6:8] != '*>':
                comments.append(text)
            continue

        # Inline comment: *> anywhere
        if '*>' in line:
            text = line.split('*>', 1)[1].strip()
            if text:
                comments.append(text)

    return comments


def _compact_comments(raw: list[str]) -> list[str]:
    """Filter decorative/boilerplate lines and compact into bullet points."""
    filtered: list[str] = []

    for line in raw:
        # Skip decorative
        if _DECORATIVE_RE.match(line):
            continue
        # Skip boilerplate
        lower = line.lower()
        if any(kw in lower for kw in _BOILERPLATE_KW):
            continue
        # Skip very short noise
        if len(line) < 3:
            continue
        filtered.append(line)

    if not filtered:
        return []

    # Collapse multi-line sentences and deduplicate
    bullets: list[str] = []
    current = filtered[0]
    seen: set[str] = set()

    for line in filtered[1:]:
        # If line looks like a continuation (starts lowercase, no bullet marker)
        if line[0].islower() and not line.startswith(('-', '*', '•')):
            current = current.rstrip('.') + ' ' + line
        else:
            norm = current.strip().lower()
            if norm not in seen:
                seen.add(norm)
                bullets.append(current.strip())
            current = line

    # Flush last
    norm = current.strip().lower()
    if norm not in seen:
        bullets.append(current.strip())

    return bullets[:5]  # Max 5 bullets per paragraph


# ---------------------------------------------------------------------------
# Agent 2: Flow Agent (deterministic)
# ---------------------------------------------------------------------------

def extract_flow_summary(
    program: Program,
    call_graph: StaticCallGraph,
    stub_mapping: dict[str, list[str]],
    gating_conds: dict[str, list],
) -> list[str]:
    """Produce a compact per-paragraph flow summary.

    Format: PARA-NAME: calls [A, B]; stubs [READ:FILE]; gated by [VAR = 'X']; branches [IF cond1]
    """
    lines: list[str] = []
    # Build reverse stub lookup: paragraph → list of op_keys
    para_stubs = _build_paragraph_stub_map(program, stub_mapping)

    for para in program.paragraphs[:60]:
        parts: list[str] = []

        # Call targets from call_graph edges
        targets = call_graph.edges.get(para.name, set())
        if targets:
            parts.append(f"calls [{', '.join(sorted(targets)[:5])}]")

        # Stub operations
        ops = para_stubs.get(para.name, [])
        if ops:
            parts.append(f"stubs [{', '.join(ops[:4])}]")

        # Gating conditions
        gates = gating_conds.get(para.name, [])
        if gates:
            gate_strs = []
            for gc in gates[:3]:
                if hasattr(gc, 'variable') and hasattr(gc, 'values'):
                    neg = "NOT " if gc.negated else ""
                    vals = ', '.join(repr(v) for v in gc.values[:3])
                    gate_strs.append(f"{neg}{gc.variable} = {vals}")
            if gate_strs:
                parts.append(f"gated by [{'; '.join(gate_strs)}]")

        # Branch conditions (from statement tree)
        branches = _extract_branch_conditions(para)
        if branches:
            parts.append(f"branches [{', '.join(branches[:3])}]")

        if parts:
            lines.append(f"{para.name}: {'; '.join(parts)}")
        else:
            lines.append(para.name)

    return lines


def _build_paragraph_stub_map(
    program: Program,
    stub_mapping: dict[str, list[str]],
) -> dict[str, list[str]]:
    """Map each paragraph to the stub operation keys it references."""
    # Build a set of all op prefixes for matching
    op_prefixes: dict[str, str] = {}
    for op_key in stub_mapping:
        # e.g. "READ:XREF-FILE" → type=READ, target=XREF-FILE
        if ':' in op_key:
            op_type, op_target = op_key.split(':', 1)
            op_prefixes[op_target.upper()] = op_key
            op_prefixes[op_type.upper()] = op_key
        else:
            op_prefixes[op_key.upper()] = op_key

    result: dict[str, list[str]] = {}

    for para in program.paragraphs:
        ops: list[str] = []
        seen: set[str] = set()
        for stmt in para.statements:
            for s in stmt.walk():
                matched = _match_stmt_to_stub(s, stub_mapping, op_prefixes)
                if matched and matched not in seen:
                    seen.add(matched)
                    ops.append(matched)
        if ops:
            result[para.name] = ops

    return result


def _match_stmt_to_stub(
    stmt: Statement,
    stub_mapping: dict[str, list[str]],
    op_prefixes: dict[str, str],
) -> str | None:
    """Try to match a statement to a stub_mapping key."""
    text_upper = stmt.text.upper() if stmt.text else ""
    stype = stmt.type.upper()

    # Direct type-based: READ, WRITE, REWRITE, DELETE
    if stype in ("READ", "WRITE", "REWRITE", "DELETE", "START",
                  "STARTBR", "READNEXT", "READPREV"):
        # Try to extract filename from text
        words = text_upper.split()
        for word in words:
            key = f"{stype}:{word}"
            if key in stub_mapping:
                return key
            if word in op_prefixes:
                return op_prefixes[word]
        # Fallback: just the type
        for k in stub_mapping:
            if k.startswith(stype + ':') or k == stype:
                return k

    # EXEC blocks
    if stype == "EXEC" or "EXEC CICS" in text_upper or "EXEC DLI" in text_upper:
        if "EXEC DLI" in text_upper or "DLI" in text_upper:
            for k in stub_mapping:
                if k.startswith("DLI"):
                    return k
        if "EXEC CICS" in text_upper:
            # Try to extract CICS command
            m = re.search(r'EXEC\s+CICS\s+(\w+)', text_upper)
            if m:
                cmd = m.group(1)
                for k in stub_mapping:
                    if cmd in k.upper():
                        return k

    # CALL statements
    if stype == "CALL" or "CALL " in text_upper:
        for k in stub_mapping:
            if k.startswith("CALL:"):
                target = k.split(':', 1)[1].upper()
                if target in text_upper:
                    return k

    return None


def _extract_branch_conditions(para: Paragraph) -> list[str]:
    """Extract short condition descriptions from IF/EVALUATE statements."""
    conditions: list[str] = []

    for stmt in para.statements:
        for s in stmt.walk():
            if s.type == "IF" and s.text:
                cond = s.text.strip()
                # Truncate long conditions
                if len(cond) > 60:
                    cond = cond[:57] + "..."
                conditions.append(f"IF {cond}")
            elif s.type == "EVALUATE" and s.text:
                cond = s.text.strip()
                if len(cond) > 40:
                    cond = cond[:37] + "..."
                conditions.append(f"EVALUATE {cond}")

    return conditions


# ---------------------------------------------------------------------------
# Agent 3: Synthesis Agent (LLM-powered)
# ---------------------------------------------------------------------------

def build_synthesis_prompt(
    program_id: str,
    comments: dict[str, list[str]],
    flow_summary: list[str],
    var_report: VariableReport,
    stub_mapping: dict[str, list[str]],
    domains: dict[str, VariableDomain],
    covered_paragraphs: set[str] | None = None,
    covered_branches: set[str] | None = None,
) -> str:
    """Build a compact prompt from agent outputs — no raw COBOL source."""

    # Flow section
    flow_block = "\n".join(flow_summary) if flow_summary else "(empty program)"

    # Paragraph annotations
    anno_lines = []
    for para_name, bullets in sorted(comments.items()):
        anno_lines.append(f"{para_name}: {'; '.join(bullets)}")
    anno_block = "\n".join(anno_lines[:50]) if anno_lines else "(no comments)"

    # Variable summary
    var_lines = []
    for name, dom in sorted(domains.items()):
        if dom.classification not in ("input", "status", "flag"):
            continue
        if dom.set_by_stub:
            continue
        extras = []
        if dom.condition_literals:
            extras.append(f"known_values={dom.condition_literals[:8]!r}")
        if dom.valid_88_values:
            extras.append(f"88_levels={dict(list(dom.valid_88_values.items())[:6])!r}")
        if dom.semantic_type != "generic":
            extras.append(f"type={dom.semantic_type}")
        if dom.max_length and dom.max_length != 10:
            extras.append(f"len={dom.max_length}")
        extra_str = f" ({', '.join(extras)})" if extras else ""
        var_lines.append(f"  {name}: {dom.classification}{extra_str}")

    var_summary = "\n".join(var_lines[:60]) if var_lines else "  (none)"
    if len(var_lines) > 60:
        var_summary += f"\n  ... and {len(var_lines) - 60} more"

    # Stub mapping summary
    stub_lines = []
    for op_key, status_vars in sorted(stub_mapping.items()):
        status_info = []
        for sv in status_vars:
            dom = domains.get(sv)
            if dom:
                vals = []
                if dom.condition_literals:
                    vals.extend(str(v) for v in dom.condition_literals[:6])
                if dom.valid_88_values:
                    for label, val in list(dom.valid_88_values.items())[:4]:
                        vals.append(f"{val}={label}")
                if vals:
                    status_info.append(f"{sv} [{', '.join(vals)}]")
                else:
                    status_info.append(sv)
            else:
                status_info.append(sv)
        stub_lines.append(f"  {op_key} -> {'; '.join(status_info)}")

    stub_summary = "\n".join(stub_lines[:40]) if stub_lines else "  (none)"

    # Coverage gaps
    coverage_section = ""
    if covered_paragraphs is not None:
        coverage_section += f"\n=== COVERAGE GAPS ===\n"
        coverage_section += f"Covered: {len(covered_paragraphs)} paragraphs\n"
        # Show uncovered paragraphs from flow_summary
        all_para_names = set()
        for line in flow_summary:
            name = line.split(':')[0].strip() if ':' in line else line.strip()
            if name:
                all_para_names.add(name)
        uncovered = sorted(all_para_names - covered_paragraphs)
        if uncovered:
            shown = uncovered[:30]
            coverage_section += f"Uncovered paragraphs: {', '.join(shown)}"
            if len(uncovered) > 30:
                coverage_section += f" ... and {len(uncovered) - 30} more"
            coverage_section += "\n"
        coverage_section += "\nFocus on reaching UNCOVERED paragraphs.\n"

    if covered_branches is not None:
        coverage_section += f"Already covered branches: {len(covered_branches)}\n"
        coverage_section += "Target branch directions not yet covered.\n"

    prompt = f"""\
You are an expert COBOL test engineer. Analyze this program's structure and
generate test states that maximize code coverage, especially targeting
error-handling paths, EVALUATE branches, and stub-dependent control flow.

=== PROGRAM: {program_id} ===

=== FLOW ===
{flow_block}

=== PARAGRAPH ANNOTATIONS ===
{anno_block}

=== INPUT VARIABLES ===
{var_summary}

=== STUB OPERATIONS ===
{stub_summary}
{coverage_section}
=== INSTRUCTIONS ===
Generate 5-10 test states, each targeting a DIFFERENT execution path through
the program.
Each test state must include:
- input_values: variable values to set before execution
- stub_overrides: operation status overrides (e.g., "READ:MYFILE" -> "23" for not-found)
- target: which paragraph or path this state is trying to reach
- reasoning: brief explanation of why these values trigger that path

For stub_overrides, use the operation keys shown above (e.g., "READ:filename",
"DLI", "EXEC:CICS:SEND", etc.) and set them to status values that trigger
specific error-handling paths:
- File status: "00"=success, "10"=EOF, "23"=not-found, "35"=not-exists
- DLI PCB: "  "=success, "GE"=not-found, "GB"=end, "II"=duplicate
- CICS EIBRESP: 0=normal, 12=not-found, 13=dup-record, 16=invreq, 22=lenerr, 27=notfnd
- SQL SQLCODE: 0=success, 100=not-found, -803=duplicate, -805=not-found

IMPORTANT: Values must be strings matching COBOL field sizes.
Respond with ONLY a JSON array, no other text:
[
  {{
    "input_values": {{"VARIABLE-NAME": "value", ...}},
    "stub_overrides": {{"OPERATION:KEY": "status", ...}},
    "target": "paragraph or path description",
    "reasoning": "brief explanation"
  }}
]"""

    return prompt


# ---------------------------------------------------------------------------
# Response parsing (unchanged from v1)
# ---------------------------------------------------------------------------

def parse_test_states(response_text: str) -> list[LLMTestState]:
    """Parse LLM JSON response into LLMTestState objects.

    Handles markdown code fences, truncated responses (partial JSON recovery).
    """
    text = response_text.strip()

    # Strip markdown code fences
    if "```" in text:
        parts = text.split("```")
        for part in parts[1::2]:
            lines = part.strip().split("\n", 1)
            if len(lines) > 1 and lines[0].strip().lower() in ("json", ""):
                text = lines[1]
            else:
                text = part
            break

    # Try direct parse
    data = None
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try to find JSON array
    if data is None:
        start = text.find("[")
        end = text.rfind("]")
        if start >= 0 and end > start:
            try:
                data = json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                # Truncated response — try to recover partial array
                data = _recover_partial_json(text[start:])

    if data is None:
        log.warning("Failed to parse LLM response as JSON")
        return []

    if not isinstance(data, list):
        data = [data]

    states = []
    for item in data:
        if not isinstance(item, dict):
            continue
        state = LLMTestState(
            input_values={
                str(k): str(v)
                for k, v in item.get("input_values", {}).items()
                if isinstance(k, str)
            },
            stub_overrides={
                str(k): str(v)
                for k, v in item.get("stub_overrides", {}).items()
                if isinstance(k, str)
            },
            target_description=str(item.get("target", "")),
            reasoning=str(item.get("reasoning", "")),
        )
        if state.input_values or state.stub_overrides:
            states.append(state)

    return states


def _recover_partial_json(text: str) -> list | None:
    """Try to recover a partial JSON array from truncated LLM output."""
    results = []
    depth = 0
    obj_start = None
    in_string = False
    escape = False

    for i, ch in enumerate(text):
        if escape:
            escape = False
            continue
        if ch == '\\' and in_string:
            escape = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue

        if ch == '{':
            if depth == 0:
                obj_start = i
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0 and obj_start is not None:
                try:
                    obj = json.loads(text[obj_start:i + 1])
                    results.append(obj)
                except json.JSONDecodeError:
                    pass
                obj_start = None

    return results if results else None


# ---------------------------------------------------------------------------
# Cache + orchestrator
# ---------------------------------------------------------------------------

def _compute_cache_key(cobol_source: str, var_names: list[str]) -> str:
    """Cache key = SHA-256 of source content + sorted variable names."""
    payload = cobol_source + "\n" + "\n".join(sorted(var_names))
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def generate_llm_test_states(
    provider,
    cobol_source_path: Path,
    program: Program,
    var_report: VariableReport,
    stub_mapping: dict[str, list[str]],
    domains: dict[str, VariableDomain],
    cache_path: Path,
    call_graph: StaticCallGraph | None = None,
    gating_conds: dict[str, list] | None = None,
    model: str | None = None,
    covered_paragraphs: set[str] | None = None,
    covered_branches: set[str] | None = None,
) -> list[LLMTestState]:
    """Orchestrate the 3-agent pipeline to generate LLM test states.

    1. Read COBOL source lines
    2. Run Comments Agent → condensed paragraph annotations
    3. Run Flow Agent → compact flow summary (needs call_graph + gating_conds)
    4. Run Synthesis Agent → prompt → LLM query → parse → list[LLMTestState]
    5. Cache + return
    """
    cobol_source_path = Path(cobol_source_path)
    cache_path = Path(cache_path)

    cobol_text = cobol_source_path.read_text(errors="replace")
    source_lines = cobol_text.splitlines()
    var_names = sorted(var_report.variables.keys())
    cache_key = _compute_cache_key(cobol_text, var_names)

    # Check cache (only for initial call without coverage gaps)
    is_gap_query = covered_paragraphs is not None and len(covered_paragraphs) > 0
    if cache_path.exists() and not is_gap_query:
        try:
            cached = json.loads(cache_path.read_text())
            if cached.get("_cache_key") == cache_key:
                states = [
                    LLMTestState(
                        input_values=entry.get("input_values", {}),
                        stub_overrides=entry.get("stub_overrides", {}),
                        target_description=entry.get("target", ""),
                        reasoning=entry.get("reasoning", ""),
                    )
                    for entry in cached.get("states", [])
                ]
                log.info("LLM test states loaded from cache: %d states", len(states))
                return states
        except Exception as e:
            log.warning("Cache read failed: %s", e)

    # Agent 1: Comments Agent
    comments = extract_paragraph_comments(program, source_lines)
    log.info("Comments agent: %d paragraphs annotated", len(comments))

    # Agent 2: Flow Agent
    if call_graph is not None:
        flow_summary = extract_flow_summary(
            program, call_graph, stub_mapping, gating_conds or {},
        )
    else:
        # Fallback: simple paragraph list with PERFORM targets
        flow_summary = _fallback_flow_summary(program)
    log.info("Flow agent: %d flow lines", len(flow_summary))

    # Agent 3: Synthesis Agent — build prompt and query LLM
    prompt = build_synthesis_prompt(
        program.program_id, comments, flow_summary,
        var_report, stub_mapping, domains,
        covered_paragraphs, covered_branches,
    )

    if not prompt:
        log.info("No content for LLM query")
        return []

    log.info("Querying LLM for test states (%d paragraphs, %d vars, prompt %d chars) ...",
             len(program.paragraphs), len(var_names), len(prompt))

    try:
        response_text, tokens = _query_llm_sync(provider, prompt, model)
        log.info("LLM response: %d chars, %d tokens", len(response_text), tokens)
    except Exception as e:
        log.error("LLM query failed: %s", e)
        return []

    states = parse_test_states(response_text)
    log.info("Parsed %d test states from LLM response", len(states))

    # Write cache (only for initial queries)
    if states and not is_gap_query:
        try:
            cache_data = {
                "_cache_key": cache_key,
                "_source_file": str(cobol_source_path),
                "states": [
                    {
                        "input_values": s.input_values,
                        "stub_overrides": s.stub_overrides,
                        "target": s.target_description,
                        "reasoning": s.reasoning,
                    }
                    for s in states
                ],
            }
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            cache_path.write_text(json.dumps(cache_data, indent=2, default=str))
            log.info("LLM test states cached to %s", cache_path)
        except Exception as e:
            log.warning("Failed to write cache: %s", e)

    return states


def _fallback_flow_summary(program: Program) -> list[str]:
    """Simple flow summary when call_graph is not available."""
    lines: list[str] = []
    for para in program.paragraphs[:60]:
        performs = []
        for stmt in para.statements:
            for s in stmt.walk():
                if s.type == "PERFORM" and s.text:
                    target = s.text.split()[0] if s.text.split() else ""
                    if target and target != para.name:
                        performs.append(target)
        if performs:
            lines.append(f"{para.name}: calls [{', '.join(performs[:5])}]")
        else:
            lines.append(para.name)
    return lines
