"""Generated Python from COBOL program COSGN00C.

Auto-generated by Specter. Do not edit.
"""

# --- Runtime helpers ---

_CALL_DEPTH_LIMIT = 500


class _GobackSignal(Exception):
    """Signal for GOBACK/STOP RUN."""
    pass


def _is_numeric(v):
    """Check if a value is numeric."""
    try:
        float(str(v))
        return True
    except (ValueError, TypeError):
        return False


def _to_num(v):
    """Coerce a value to a number for arithmetic."""
    if isinstance(v, (int, float)):
        return v
    try:
        return int(v)
    except (ValueError, TypeError):
        try:
            return float(v)
        except (ValueError, TypeError):
            return 0


def _apply_stub_outcome(state, key):
    """Apply a queued stub outcome (set status variables after external op)."""
    _applied = None
    _ol = state.get('_stub_outcomes', {}).get(key, [])
    if _ol:
        _entry = _ol.pop(0)
        _applied = _entry
        if isinstance(_entry, list):
            for _var, _val in _entry:
                state[_var] = _val
        else:
            _var, _val = _entry
            state[_var] = _val
    else:
        # Apply default when stub outcomes exhausted
        _dm = state.get('_stub_defaults', {}).get(key)
        if _dm:
            _applied = list(_dm)
            for _var, _val in _dm:
                state[_var] = _val
    _log = state.get('_stub_log')
    if _log is not None:
        _log.append((key, _applied))


def _dummy_call(name, state, *args):
    """Stub for external CALL."""
    state['_calls'].append({'name': name, 'args': list(args)})
    _apply_stub_outcome(state, 'CALL:' + name)


def _dummy_exec(kind, raw_text, state):
    """Stub for EXEC SQL/CICS/DLI."""
    state['_execs'].append({'kind': kind, 'text': raw_text})
    _apply_stub_outcome(state, kind)


class _SafeDict(dict):
    def __getitem__(self, key):
        try:
            return super().__getitem__(key)
        except KeyError:
            return ''


class _InstrumentedState(_SafeDict):
    """Dict subclass that records variable reads/writes and paragraph trace."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._current_para = ''
        self._call_stack = []
        super().__setitem__('_trace', [])
        super().__setitem__('_var_writes', [])
        super().__setitem__('_var_reads', [])
        super().__setitem__('_call_events', [])

    def _enter_para(self, name):
        if len(self['_trace']) > 50000:
            raise _GobackSignal()
        caller = self._call_stack[-1] if self._call_stack else None
        self._call_stack.append(name)
        self._current_para = name
        super().__getitem__('_trace').append(name)
        super().__getitem__('_call_events').append(('enter', name, len(self._call_stack), caller))

    def _exit_para(self, name):
        if self._call_stack and self._call_stack[-1] == name:
            self._call_stack.pop()
        self._current_para = self._call_stack[-1] if self._call_stack else ''
        super().__getitem__('_call_events').append(('exit', name, len(self._call_stack) + 1, None))

    def __setitem__(self, key, value):
        if not key.startswith('_'):
            super().__getitem__('_var_writes').append((key, self._current_para))
        super().__setitem__(key, value)

    def get(self, key, default=None):
        if not key.startswith('_'):
            super().__getitem__('_var_reads').append((key, self._current_para))
        return super().get(key, default)

    def __getitem__(self, key):
        if not key.startswith('_'):
            dict.__getitem__(self, '_var_reads').append((key, self._current_para))
        return super().__getitem__(key)

    def setdefault(self, key, default=None):
        if key not in self:
            self[key] = default
        return super().__getitem__(key)


def _default_state():
    """Return default state dict with all discovered variables."""
    return {
        'CCDA-MSG-INVALID-KEY': '',
        'CCDA-MSG-THANK-YOU': '',
        'CCDA-TITLE01': '',
        'CCDA-TITLE02': '',
        'CDEMO-FROM-PROGRAM': '',
        'CDEMO-FROM-TRANID': '',
        'CDEMO-PGM-CONTEXT': '',
        'CDEMO-USER-ID': '',
        'CDEMO-USER-TYPE': '',
        'CDEMO-USRTYP-ADMIN': '',
        'COSGN0AI': '',
        'COSGN0AO': '',
        'CURDATEO': '',
        'CURRENT-DATE': '',
        'CURTIMEO': 0,
        'EIBAID': ' ',
        'EIBCALEN': ' ',
        'ERR-FLG-OFF': False,
        'ERR-FLG-ON': False,
        'ERRMSGO': '',
        'PASSWDI': '',
        'PASSWDL': '',
        'PGMNAMEO': '',
        'SEC-USR-PWD': '',
        'SEC-USR-TYPE': '',
        'THE': '',
        'TITLE01O': '',
        'TITLE02O': '',
        'TRNNAMEO': '',
        'UPPER-CASE': '',
        'USER': '',
        'USERIDI': '',
        'USERIDL': '',
        'VERIFY': '',
        'WS-CURDATE-DATA': '',
        'WS-CURDATE-DAY': '',
        'WS-CURDATE-DD': '',
        'WS-CURDATE-MM': '',
        'WS-CURDATE-MM-DD-YY': '',
        'WS-CURDATE-MONTH': '',
        'WS-CURDATE-YEAR': '',
        'WS-CURDATE-YY': '',
        'WS-CURTIME-HH': 0,
        'WS-CURTIME-HH-MM-SS': 0,
        'WS-CURTIME-HOURS': 0,
        'WS-CURTIME-MINUTE': 0,
        'WS-CURTIME-MM': 0,
        'WS-CURTIME-SECOND': 0,
        'WS-CURTIME-SS': 0,
        'WS-ERR-FLG': False,
        'WS-MESSAGE': '',
        'WS-PGMNAME': '',
        'WS-RESP-CD': '',
        'WS-TRANID': '',
        'WS-USER-ID': '',
        'WS-USER-PWD': '',
    }


def para_MAIN_PARA(state):
    """Paragraph MAIN-PARA (lines 73-102)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('MAIN-PARA')
        state['ERR-FLG-OFF'] = True
        state['WS-MESSAGE'] = ' '
        if state['EIBCALEN'] == 0:
            state.get('_branches', set()).add(1)
            state['COSGN0AO'] = ''
            state['USERIDL'] = -1
            state['OF'] = -1
            state['COSGN0AI'] = -1
            para_SEND_SIGNON_SCREEN(state)
        else:
            state.get('_branches', set()).add(-1)
            _eval_subject = state.get('EIBAID', '')
            if _eval_subject == 'DFHENTER':
                state.get('_branches', set()).add(2)
                para_PROCESS_ENTER_KEY(state)
            elif _eval_subject == 'DFHPF3':
                state.get('_branches', set()).add(3)
                state['WS-MESSAGE'] = state.get('CCDA-MSG-THANK-YOU', '')
                para_SEND_PLAIN_TEXT(state)
            else:
                state.get('_branches', set()).add(4)
                state['WS-ERR-FLG'] = 'Y'
                state['WS-MESSAGE'] = state.get('CCDA-MSG-INVALID-KEY', '')
                para_SEND_SIGNON_SCREEN(state)
        _dummy_exec('CICS', 'EXEC CICS RETURN TRANSID (WS-TRANID) COMMAREA (CARDDEMO-COMMAREA) LENGTH(LENGTH OF CARDDEMO-COMMAREA) END-EXEC.', state)
    finally:
        state._exit_para('MAIN-PARA')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_PROCESS_ENTER_KEY(state):
    """Paragraph PROCESS-ENTER-KEY (lines 108-140)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('PROCESS-ENTER-KEY')
        _dummy_exec('CICS', 'EXEC CICS RECEIVE MAP(\'COSGN0A\') MAPSET(\'COSGN00\') RESP(WS-RESP-CD) RESP2(WS-REAS-CD) END-EXEC.', state)
        if state['USERIDI']:
            state.get('_branches', set()).add(5)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'Please enter User ID ...'
            state['USERIDL'] = -1
            state['OF'] = -1
            state['COSGN0AI'] = -1
            para_SEND_SIGNON_SCREEN(state)
        elif state['PASSWDI']:
            state.get('_branches', set()).add(6)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'Please enter Password ...'
            state['PASSWDL'] = -1
            state['OF'] = -1
            state['COSGN0AI'] = -1
            para_SEND_SIGNON_SCREEN(state)
        else:
            state.get('_branches', set()).add(7)
            pass  # CONTINUE
        state['WS-USER-ID'] = state.get('FUNCTION UPPER-CASE(USERIDI OF COSGN0AI)', '')
        state['WS-USER-PWD'] = state.get('FUNCTION UPPER-CASE(PASSWDI OF COSGN0AI)', '')
        if not (state['ERR-FLG-ON']):
            state.get('_branches', set()).add(8)
            para_READ_USER_SEC_FILE(state)
        else:
            state.get('_branches', set()).add(-8)
    finally:
        state._exit_para('PROCESS-ENTER-KEY')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_SEND_SIGNON_SCREEN(state):
    """Paragraph SEND-SIGNON-SCREEN (lines 145-157)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('SEND-SIGNON-SCREEN')
        para_POPULATE_HEADER_INFO(state)
        state['ERRMSGO'] = state.get('WS-MESSAGE', '')
        state['OF'] = state.get('WS-MESSAGE', '')
        state['COSGN0AO'] = state.get('WS-MESSAGE', '')
        _dummy_exec('CICS', 'EXEC CICS SEND MAP(\'COSGN0A\') MAPSET(\'COSGN00\') FROM(COSGN0AO) ERASE CURSOR END-EXEC.', state)
    finally:
        state._exit_para('SEND-SIGNON-SCREEN')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_SEND_PLAIN_TEXT(state):
    """Paragraph SEND-PLAIN-TEXT (lines 162-172)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('SEND-PLAIN-TEXT')
        _dummy_exec('CICS', 'EXEC CICS SEND TEXT FROM(WS-MESSAGE) LENGTH(LENGTH OF WS-MESSAGE) ERASE FREEKB END-EXEC.', state)
        _dummy_exec('CICS', 'EXEC CICS RETURN END-EXEC.', state)
    finally:
        state._exit_para('SEND-PLAIN-TEXT')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_POPULATE_HEADER_INFO(state):
    """Paragraph POPULATE-HEADER-INFO (lines 177-204)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('POPULATE-HEADER-INFO')
        state['WS-CURDATE-DATA'] = state.get('FUNCTION CURRENT-DATE', '')
        state['TITLE01O'] = state.get('CCDA-TITLE01', '')
        state['OF'] = state.get('CCDA-TITLE01', '')
        state['COSGN0AO'] = state.get('CCDA-TITLE01', '')
        state['TITLE02O'] = state.get('CCDA-TITLE02', '')
        state['OF'] = state.get('CCDA-TITLE02', '')
        state['COSGN0AO'] = state.get('CCDA-TITLE02', '')
        state['TRNNAMEO'] = state.get('WS-TRANID', '')
        state['OF'] = state.get('WS-TRANID', '')
        state['COSGN0AO'] = state.get('WS-TRANID', '')
        state['PGMNAMEO'] = state.get('WS-PGMNAME', '')
        state['OF'] = state.get('WS-PGMNAME', '')
        state['COSGN0AO'] = state.get('WS-PGMNAME', '')
        state['WS-CURDATE-MM'] = state.get('WS-CURDATE-MONTH', '')
        state['WS-CURDATE-DD'] = state.get('WS-CURDATE-DAY', '')
        state['WS-CURDATE-YY'] = str(state.get('WS-CURDATE-YEAR', ''))[2:4]
        state['CURDATEO'] = state.get('WS-CURDATE-MM-DD-YY', '')
        state['OF'] = state.get('WS-CURDATE-MM-DD-YY', '')
        state['COSGN0AO'] = state.get('WS-CURDATE-MM-DD-YY', '')
        state['WS-CURTIME-HH'] = state.get('WS-CURTIME-HOURS', '')
        state['WS-CURTIME-MM'] = state.get('WS-CURTIME-MINUTE', '')
        state['WS-CURTIME-SS'] = state.get('WS-CURTIME-SECOND', '')
        state['CURTIMEO'] = state.get('WS-CURTIME-HH-MM-SS', '')
        state['OF'] = state.get('WS-CURTIME-HH-MM-SS', '')
        state['COSGN0AO'] = state.get('WS-CURTIME-HH-MM-SS', '')
        _dummy_exec('CICS', 'EXEC CICS ASSIGN APPLID(APPLIDO OF COSGN0AO) END-EXEC', state)
        _dummy_exec('CICS', 'EXEC CICS ASSIGN SYSID(SYSIDO OF COSGN0AO) END-EXEC.', state)
    finally:
        state._exit_para('POPULATE-HEADER-INFO')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_READ_USER_SEC_FILE(state):
    """Paragraph READ-USER-SEC-FILE (lines 209-257)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('READ-USER-SEC-FILE')
        _dummy_exec('CICS', 'EXEC CICS READ DATASET   (WS-USRSEC-FILE) INTO      (SEC-USER-DATA) LENGTH    (LENGTH OF SEC-USER-DATA) RIDFLD    (WS-USER-ID) KEYLENGTH (LENGTH OF WS-USER-ID) RESP      (WS-RESP-CD) RESP2     (WS-REA...', state)
        _eval_subject = state.get('WS-RESP-CD', '')
        _eval_subject = _to_num(_eval_subject)
        if _eval_subject == 0:
            state.get('_branches', set()).add(9)
            if state['SEC-USR-PWD'] == state['WS-USER-PWD']:
                state.get('_branches', set()).add(10)
                state['CDEMO-FROM-TRANID'] = state.get('WS-TRANID', '')
                state['CDEMO-FROM-PROGRAM'] = state.get('WS-PGMNAME', '')
                state['CDEMO-USER-ID'] = state.get('WS-USER-ID', '')
                state['CDEMO-USER-TYPE'] = state.get('SEC-USR-TYPE', '')
                state['CDEMO-PGM-CONTEXT'] = 0
                if state['CDEMO-USRTYP-ADMIN']:
                    state.get('_branches', set()).add(11)
                    _dummy_exec('CICS', 'EXEC CICS XCTL PROGRAM (\'COADM01C\') COMMAREA(CARDDEMO-COMMAREA) END-EXEC', state)
                else:
                    state.get('_branches', set()).add(-11)
                    _dummy_exec('CICS', 'EXEC CICS XCTL PROGRAM (\'COMEN01C\') COMMAREA(CARDDEMO-COMMAREA) END-EXEC', state)
            else:
                state.get('_branches', set()).add(-10)
                state['WS-MESSAGE'] = 'Wrong Password. Try again ...'
                state['PASSWDL'] = -1
                state['OF'] = -1
                state['COSGN0AI'] = -1
                para_SEND_SIGNON_SCREEN(state)
        elif _eval_subject == 13:
            state.get('_branches', set()).add(12)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'User not found. Try again ...'
            state['USERIDL'] = -1
            state['OF'] = -1
            state['COSGN0AI'] = -1
            para_SEND_SIGNON_SCREEN(state)
        else:
            state.get('_branches', set()).add(13)
            state['WS-ERR-FLG'] = 'Y'
            state['VERIFY'] = state.get('UNABLE', '')
            state['THE'] = state.get('UNABLE', '')
            state['USER'] = state.get('UNABLE', '')
            state['TO'] = state.get('UNABLE', '')
            state['WS-MESSAGE'] = state.get('UNABLE', '')
            state['USERIDL'] = -1
            state['OF'] = -1
            state['COSGN0AI'] = -1
            para_SEND_SIGNON_SCREEN(state)
    finally:
        state._exit_para('READ-USER-SEC-FILE')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


_BRANCH_META = {1: {'condition': 'EIBCALEN = 0', 'paragraph': 'MAIN-PARA', 'type': 'IF'}, 2: {'condition': 'DFHENTER', 'paragraph': 'MAIN-PARA', 'type': 'EVALUATE', 'subject': 'EIBAID'}, 3: {'condition': 'DFHPF3', 'paragraph': 'MAIN-PARA', 'type': 'EVALUATE', 'subject': 'EIBAID'}, 4: {'condition': 'OTHER', 'paragraph': 'MAIN-PARA', 'type': 'EVALUATE', 'subject': 'EIBAID'}, 5: {'condition': 'USERIDI OF COSGN0AI = SPACES OR LOW-VALUES', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 6: {'condition': 'PASSWDI OF COSGN0AI = SPACES OR LOW-VALUES', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 7: {'condition': 'OTHER', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 8: {'condition': 'NOT ERR-FLG-ON', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'IF'}, 9: {'condition': '0', 'paragraph': 'READ-USER-SEC-FILE', 'type': 'EVALUATE', 'subject': 'WS-RESP-CD'}, 10: {'condition': 'SEC-USR-PWD = WS-USER-PWD', 'paragraph': 'READ-USER-SEC-FILE', 'type': 'IF'}, 11: {'condition': 'CDEMO-USRTYP-ADMIN', 'paragraph': 'READ-USER-SEC-FILE', 'type': 'IF'}, 12: {'condition': '13', 'paragraph': 'READ-USER-SEC-FILE', 'type': 'EVALUATE', 'subject': 'WS-RESP-CD'}, 13: {'condition': 'OTHER', 'paragraph': 'READ-USER-SEC-FILE', 'type': 'EVALUATE', 'subject': 'WS-RESP-CD'}}


def run(initial_state=None):
    """Execute the program with optional initial state overrides."""
    state = _InstrumentedState({**_default_state(), **(initial_state or {})})
    state.setdefault('_display', [])
    state.setdefault('_calls', [])
    state.setdefault('_execs', [])
    state.setdefault('_reads', [])
    state.setdefault('_writes', [])
    state.setdefault('_abended', False)
    state.setdefault('_branches', set())
    state.setdefault('_stub_log', [])
    dict.__setitem__(state, '_initial_snapshot', {k: v for k, v in state.items() if not k.startswith('_')})
    try:
        para_MAIN_PARA(state)
        para_PROCESS_ENTER_KEY(state)
        para_SEND_SIGNON_SCREEN(state)
        para_SEND_PLAIN_TEXT(state)
        para_POPULATE_HEADER_INFO(state)
        para_READ_USER_SEC_FILE(state)
    except _GobackSignal:
        pass
    except ZeroDivisionError:
        state['_abended'] = True
    _snap = dict.__getitem__(state, '_initial_snapshot')
    state['_state_diffs'] = {
        k: {'from': _snap[k], 'to': dict.__getitem__(state, k)}
        for k in _snap
        if _snap[k] != dict.get(state, k)
    }
    return state


if __name__ == '__main__':
    result = run()
    for line in result.get('_display', []):
        print(line)

