"""Generated Python from COBOL program COUSR01C.

Auto-generated by Specter. Do not edit.
"""

# --- Runtime helpers ---

_CALL_DEPTH_LIMIT = 500


class _GobackSignal(Exception):
    """Signal for GOBACK/STOP RUN."""
    pass


def _is_numeric(v):
    """Check if a value is numeric."""
    try:
        float(str(v))
        return True
    except (ValueError, TypeError):
        return False


def _to_num(v):
    """Coerce a value to a number for arithmetic."""
    if isinstance(v, (int, float)):
        return v
    try:
        return int(v)
    except (ValueError, TypeError):
        try:
            return float(v)
        except (ValueError, TypeError):
            return 0


def _apply_stub_outcome(state, key):
    """Apply a queued stub outcome (set status variables after external op)."""
    _applied = None
    _ol = state.get('_stub_outcomes', {}).get(key, [])
    if _ol:
        _entry = _ol.pop(0)
        _applied = _entry
        if isinstance(_entry, list):
            for _var, _val in _entry:
                state[_var] = _val
        else:
            _var, _val = _entry
            state[_var] = _val
    else:
        # Apply default when stub outcomes exhausted
        _dm = state.get('_stub_defaults', {}).get(key)
        if _dm:
            _applied = list(_dm)
            for _var, _val in _dm:
                state[_var] = _val
    _log = state.get('_stub_log')
    if _log is not None:
        _log.append((key, _applied))


def _dummy_call(name, state, *args):
    """Stub for external CALL."""
    state['_calls'].append({'name': name, 'args': list(args)})
    _apply_stub_outcome(state, 'CALL:' + name)


def _dummy_exec(kind, raw_text, state):
    """Stub for EXEC SQL/CICS/DLI."""
    state['_execs'].append({'kind': kind, 'text': raw_text})
    _apply_stub_outcome(state, kind)


class _SafeDict(dict):
    def __getitem__(self, key):
        try:
            return super().__getitem__(key)
        except KeyError:
            return ''


class _InstrumentedState(_SafeDict):
    """Dict subclass that records variable reads/writes and paragraph trace."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._current_para = ''
        self._call_stack = []
        super().__setitem__('_trace', [])
        super().__setitem__('_var_writes', [])
        super().__setitem__('_var_reads', [])
        super().__setitem__('_call_events', [])

    def _enter_para(self, name):
        if len(self['_trace']) > 50000:
            raise _GobackSignal()
        caller = self._call_stack[-1] if self._call_stack else None
        self._call_stack.append(name)
        self._current_para = name
        super().__getitem__('_trace').append(name)
        super().__getitem__('_call_events').append(('enter', name, len(self._call_stack), caller))

    def _exit_para(self, name):
        if self._call_stack and self._call_stack[-1] == name:
            self._call_stack.pop()
        self._current_para = self._call_stack[-1] if self._call_stack else ''
        super().__getitem__('_call_events').append(('exit', name, len(self._call_stack) + 1, None))

    def __setitem__(self, key, value):
        if not key.startswith('_'):
            super().__getitem__('_var_writes').append((key, self._current_para))
        super().__setitem__(key, value)

    def get(self, key, default=None):
        if not key.startswith('_'):
            super().__getitem__('_var_reads').append((key, self._current_para))
        return super().get(key, default)

    def __getitem__(self, key):
        if not key.startswith('_'):
            dict.__getitem__(self, '_var_reads').append((key, self._current_para))
        return super().__getitem__(key)

    def setdefault(self, key, default=None):
        if key not in self:
            self[key] = default
        return super().__getitem__(key)


def _default_state():
    """Return default state dict with all discovered variables."""
    return {
        'CARDDEMO-COMMAREA': '',
        'CCDA-MSG-INVALID-KEY': '',
        'CCDA-TITLE01': '',
        'CCDA-TITLE02': '',
        'CDEMO-FROM-PROGRAM': '',
        'CDEMO-FROM-TRANID': '',
        'CDEMO-PGM-CONTEXT': '',
        'CDEMO-PGM-REENTER': '',
        'CDEMO-TO-PROGRAM': '',
        'COUSR1AI': '',
        'COUSR1AO': '',
        'CURDATEO': '',
        'CURRENT-DATE': '',
        'CURTIMEO': 0,
        'DFHCOMMAREA': '',
        'DFHGREEN': '',
        'DFHRESP': '',
        'DUPKEY': '',
        'EIBAID': ' ',
        'EIBCALEN': ' ',
        'ERR-FLG-OFF': False,
        'ERR-FLG-ON': False,
        'ERRMSGC': '',
        'ERRMSGO': '',
        'FNAMEI': '',
        'FNAMEL': '',
        'LNAMEI': '',
        'LNAMEL': '',
        'NORMAL': '',
        'PASSWDI': '',
        'PASSWDL': '',
        'PGMNAMEO': '',
        'SEC-USR-FNAME': '',
        'SEC-USR-ID': '',
        'SEC-USR-LNAME': '',
        'SEC-USR-PWD': '',
        'SEC-USR-TYPE': '',
        'TITLE01O': '',
        'TITLE02O': '',
        'TRNNAMEO': '',
        'USERIDI': '',
        'USERIDL': '',
        'USRTYPEI': '',
        'USRTYPEL': '',
        'WS-CURDATE-DATA': '',
        'WS-CURDATE-DAY': '',
        'WS-CURDATE-DD': '',
        'WS-CURDATE-MM': '',
        'WS-CURDATE-MM-DD-YY': '',
        'WS-CURDATE-MONTH': '',
        'WS-CURDATE-YEAR': '',
        'WS-CURDATE-YY': '',
        'WS-CURTIME-HH': 0,
        'WS-CURTIME-HH-MM-SS': 0,
        'WS-CURTIME-HOURS': 0,
        'WS-CURTIME-MINUTE': 0,
        'WS-CURTIME-MM': 0,
        'WS-CURTIME-SECOND': 0,
        'WS-CURTIME-SS': 0,
        'WS-ERR-FLG': False,
        'WS-MESSAGE': '',
        'WS-PGMNAME': '',
        'WS-RESP-CD': '',
        'WS-TRANID': '',
    }


def para_MAIN_PARA(state):
    """Paragraph MAIN-PARA (lines 419-458)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('MAIN-PARA')
        state['ERR-FLG-OFF'] = True
        state['WS-MESSAGE'] = ' '
        state['ERRMSGO'] = ' '
        if state['EIBCALEN'] == 0:
            state.get('_branches', set()).add(1)
            state['CDEMO-TO-PROGRAM'] = 'COSGN00C'
            para_RETURN_TO_PREV_SCREEN(state)
        else:
            state.get('_branches', set()).add(-1)
            state['CARDDEMO-COMMAREA'] = state.get('DFHCOMMAREA(1:EIBCALEN)', '')
            if not (state['CDEMO-PGM-REENTER']):
                state.get('_branches', set()).add(2)
                state['CDEMO-PGM-REENTER'] = True
                state['COUSR1AO'] = ''
                state['FNAMEL'] = -1
                para_SEND_USRADD_SCREEN(state)
            else:
                state.get('_branches', set()).add(-2)
                para_RECEIVE_USRADD_SCREEN(state)
                _eval_subject = state.get('EIBAID', '')
                if (_eval_subject == 'DFHENTER'):
                    state.get('_branches', set()).add(3)
                    para_PROCESS_ENTER_KEY(state)
                elif (_eval_subject == 'DFHPF3'):
                    state.get('_branches', set()).add(4)
                    state['CDEMO-TO-PROGRAM'] = 'COADM01C'
                    para_RETURN_TO_PREV_SCREEN(state)
                elif (_eval_subject == 'DFHPF4'):
                    state.get('_branches', set()).add(5)
                    para_CLEAR_CURRENT_SCREEN(state)
                else:
                    state.get('_branches', set()).add(6)
                    state['WS-ERR-FLG'] = 'Y'
                    state['FNAMEL'] = -1
                    state['WS-MESSAGE'] = state.get('CCDA-MSG-INVALID-KEY', '')
                    para_SEND_USRADD_SCREEN(state)
        _dummy_exec('CICS', 'EXEC CICS RETURN TRANSID (WS-TRANID) COMMAREA (CARDDEMO-COMMAREA) END-EXEC', state)
    finally:
        state._exit_para('MAIN-PARA')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_PROCESS_ENTER_KEY(state):
    """Paragraph PROCESS-ENTER-KEY (lines 463-508)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('PROCESS-ENTER-KEY')
        if (state['FNAMEI']):
            state.get('_branches', set()).add(7)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'First Name can NOT be empty...'
            state['FNAMEL'] = -1
            para_SEND_USRADD_SCREEN(state)
        elif (state['LNAMEI']):
            state.get('_branches', set()).add(8)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'Last Name can NOT be empty...'
            state['LNAMEL'] = -1
            para_SEND_USRADD_SCREEN(state)
        elif (state['USERIDI']):
            state.get('_branches', set()).add(9)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'User ID can NOT be empty...'
            state['USERIDL'] = -1
            para_SEND_USRADD_SCREEN(state)
        elif (state['PASSWDI']):
            state.get('_branches', set()).add(10)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'Password can NOT be empty...'
            state['PASSWDL'] = -1
            para_SEND_USRADD_SCREEN(state)
        elif (state['USRTYPEI']):
            state.get('_branches', set()).add(11)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'User Type can NOT be empty...'
            state['USRTYPEL'] = -1
            para_SEND_USRADD_SCREEN(state)
        else:
            state.get('_branches', set()).add(12)
            state['FNAMEL'] = -1
            pass  # CONTINUE
        if not (state['ERR-FLG-ON']):
            state.get('_branches', set()).add(13)
            state['SEC-USR-ID'] = state.get('USERIDI OF COUSR1AI', '')
            state['SEC-USR-FNAME'] = state.get('FNAMEI OF COUSR1AI', '')
            state['SEC-USR-LNAME'] = state.get('LNAMEI OF COUSR1AI', '')
            state['SEC-USR-PWD'] = state.get('PASSWDI OF COUSR1AI', '')
            state['SEC-USR-TYPE'] = state.get('USRTYPEI OF COUSR1AI', '')
            para_WRITE_USER_SEC_FILE(state)
        else:
            state.get('_branches', set()).add(-13)
    finally:
        state._exit_para('PROCESS-ENTER-KEY')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_RETURN_TO_PREV_SCREEN(state):
    """Paragraph RETURN-TO-PREV-SCREEN (lines 513-526)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('RETURN-TO-PREV-SCREEN')
        if state['CDEMO-TO-PROGRAM'] in ('', ' '):
            state.get('_branches', set()).add(14)
            state['CDEMO-TO-PROGRAM'] = 'COSGN00C'
        else:
            state.get('_branches', set()).add(-14)
        state['CDEMO-FROM-TRANID'] = state.get('WS-TRANID', '')
        state['CDEMO-FROM-PROGRAM'] = state.get('WS-PGMNAME', '')
        state['CDEMO-PGM-CONTEXT'] = 0
        _dummy_exec('CICS', 'EXEC CICS XCTL PROGRAM(CDEMO-TO-PROGRAM) COMMAREA(CARDDEMO-COMMAREA) END-EXEC', state)
    finally:
        state._exit_para('RETURN-TO-PREV-SCREEN')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_SEND_USRADD_SCREEN(state):
    """Paragraph SEND-USRADD-SCREEN (lines 532-544)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('SEND-USRADD-SCREEN')
        para_POPULATE_HEADER_INFO(state)
        state['ERRMSGO'] = state.get('WS-MESSAGE', '')
        _dummy_exec('CICS', 'EXEC CICS SEND MAP(\'COUSR1A\') MAPSET(\'COUSR01\') FROM(COUSR1AO) ERASE CURSOR END-EXEC', state)
    finally:
        state._exit_para('SEND-USRADD-SCREEN')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_RECEIVE_USRADD_SCREEN(state):
    """Paragraph RECEIVE-USRADD-SCREEN (lines 549-557)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('RECEIVE-USRADD-SCREEN')
        _dummy_exec('CICS', 'EXEC CICS RECEIVE MAP(\'COUSR1A\') MAPSET(\'COUSR01\') INTO(COUSR1AI) RESP(WS-RESP-CD) RESP2(WS-REAS-CD) END-EXEC', state)
    finally:
        state._exit_para('RECEIVE-USRADD-SCREEN')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_POPULATE_HEADER_INFO(state):
    """Paragraph POPULATE-HEADER-INFO (lines 562-581)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('POPULATE-HEADER-INFO')
        state['WS-CURDATE-DATA'] = state.get('FUNCTION CURRENT-DATE', '')
        state['TITLE01O'] = state.get('CCDA-TITLE01', '')
        state['TITLE02O'] = state.get('CCDA-TITLE02', '')
        state['TRNNAMEO'] = state.get('WS-TRANID', '')
        state['PGMNAMEO'] = state.get('WS-PGMNAME', '')
        state['WS-CURDATE-MM'] = state.get('WS-CURDATE-MONTH', '')
        state['WS-CURDATE-DD'] = state.get('WS-CURDATE-DAY', '')
        state['WS-CURDATE-YY'] = str(state.get('WS-CURDATE-YEAR', ''))[2:4]
        state['CURDATEO'] = state.get('WS-CURDATE-MM-DD-YY', '')
        state['WS-CURTIME-HH'] = state.get('WS-CURTIME-HOURS', '')
        state['WS-CURTIME-MM'] = state.get('WS-CURTIME-MINUTE', '')
        state['WS-CURTIME-SS'] = state.get('WS-CURTIME-SECOND', '')
        state['CURTIMEO'] = state.get('WS-CURTIME-HH-MM-SS', '')
    finally:
        state._exit_para('POPULATE-HEADER-INFO')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_WRITE_USER_SEC_FILE(state):
    """Paragraph WRITE-USER-SEC-FILE (lines 586-622)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('WRITE-USER-SEC-FILE')
        _dummy_exec('CICS', 'EXEC CICS WRITE DATASET   (WS-USRSEC-FILE) FROM      (SEC-USER-DATA) LENGTH    (LENGTH OF SEC-USER-DATA) RIDFLD    (SEC-USR-ID) KEYLENGTH (LENGTH OF SEC-USR-ID) RESP      (WS-RESP-CD) RESP2     (WS-RE...', state)
        _eval_subject = state.get('WS-RESP-CD', '')
        if (_eval_subject == 0):
            state.get('_branches', set()).add(15)
            para_INITIALIZE_ALL_FIELDS(state)
            state['WS-MESSAGE'] = ' '
            state['ERRMSGC'] = state.get('DFHGREEN', '')
            state['WS-MESSAGE'] = 'User ' + str(state.get('SEC-USR-ID', '')) + str(state.get('DELIMITED', '')) + str(state.get('BY', '')) + str(state.get('SPACE', '')) + ' has been added ...'
            para_SEND_USRADD_SCREEN(state)
        elif (_eval_subject == 15):
            state.get('_branches', set()).add(16)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'User ID already exist...'
            state['USERIDL'] = -1
            para_SEND_USRADD_SCREEN(state)
        else:
            state.get('_branches', set()).add(17)
            state['WS-ERR-FLG'] = 'Y'
            state['WS-MESSAGE'] = 'Unable to Add User...'
            state['FNAMEL'] = -1
            para_SEND_USRADD_SCREEN(state)
    finally:
        state._exit_para('WRITE-USER-SEC-FILE')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_CLEAR_CURRENT_SCREEN(state):
    """Paragraph CLEAR-CURRENT-SCREEN (lines 627-630)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('CLEAR-CURRENT-SCREEN')
        para_INITIALIZE_ALL_FIELDS(state)
        para_SEND_USRADD_SCREEN(state)
    finally:
        state._exit_para('CLEAR-CURRENT-SCREEN')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


def para_INITIALIZE_ALL_FIELDS(state):
    """Paragraph INITIALIZE-ALL-FIELDS (lines 635-643)."""
    _d = state.get('_call_depth', 0) + 1
    state['_call_depth'] = _d
    if _d > _CALL_DEPTH_LIMIT:
        state['_call_depth'] = _d - 1
        return
    try:
        state._enter_para('INITIALIZE-ALL-FIELDS')
        state['FNAMEL'] = -1
        state['USERIDI'] = ' '
        state['FNAMEI'] = ' '
        state['LNAMEI'] = ' '
        state['PASSWDI'] = ' '
        state['USRTYPEI'] = ' '
        state['WS-MESSAGE'] = ' '
    finally:
        state._exit_para('INITIALIZE-ALL-FIELDS')
        state['_call_depth'] = state.get('_call_depth', 1) - 1


_BRANCH_META = {1: {'condition': 'EIBCALEN = 0', 'paragraph': 'MAIN-PARA', 'type': 'IF'}, 2: {'condition': 'NOT CDEMO-PGM-REENTER', 'paragraph': 'MAIN-PARA', 'type': 'IF'}, 3: {'condition': 'DFHENTER', 'paragraph': 'MAIN-PARA', 'type': 'EVALUATE', 'subject': 'EIBAID'}, 4: {'condition': 'DFHPF3', 'paragraph': 'MAIN-PARA', 'type': 'EVALUATE', 'subject': 'EIBAID'}, 5: {'condition': 'DFHPF4', 'paragraph': 'MAIN-PARA', 'type': 'EVALUATE', 'subject': 'EIBAID'}, 6: {'condition': 'OTHER', 'paragraph': 'MAIN-PARA', 'type': 'EVALUATE', 'subject': 'EIBAID'}, 7: {'condition': 'FNAMEI OF COUSR1AI = SPACES OR LOW-VALUES', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 8: {'condition': 'LNAMEI OF COUSR1AI = SPACES OR LOW-VALUES', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 9: {'condition': 'USERIDI OF COUSR1AI = SPACES OR LOW-VALUES', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 10: {'condition': 'PASSWDI OF COUSR1AI = SPACES OR LOW-VALUES', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 11: {'condition': 'USRTYPEI OF COUSR1AI = SPACES OR LOW-VALUES', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 12: {'condition': 'OTHER', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'EVALUATE', 'subject': 'TRUE'}, 13: {'condition': 'NOT ERR-FLG-ON', 'paragraph': 'PROCESS-ENTER-KEY', 'type': 'IF'}, 14: {'condition': 'CDEMO-TO-PROGRAM = LOW-VALUES OR SPACES', 'paragraph': 'RETURN-TO-PREV-SCREEN', 'type': 'IF'}, 15: {'condition': 'DFHRESP(NORMAL)', 'paragraph': 'WRITE-USER-SEC-FILE', 'type': 'EVALUATE', 'subject': 'WS-RESP-CD'}, 16: {'condition': 'DFHRESP(DUPKEY)', 'paragraph': 'WRITE-USER-SEC-FILE', 'type': 'EVALUATE', 'subject': 'WS-RESP-CD'}, 17: {'condition': 'OTHER', 'paragraph': 'WRITE-USER-SEC-FILE', 'type': 'EVALUATE', 'subject': 'WS-RESP-CD'}}


def run(initial_state=None):
    """Execute the program with optional initial state overrides."""
    state = _InstrumentedState({**_default_state(), **(initial_state or {})})
    state.setdefault('_display', [])
    state.setdefault('_calls', [])
    state.setdefault('_execs', [])
    state.setdefault('_reads', [])
    state.setdefault('_writes', [])
    state.setdefault('_abended', False)
    state.setdefault('_branches', set())
    state.setdefault('_stub_log', [])
    dict.__setitem__(state, '_initial_snapshot', {k: v for k, v in state.items() if not k.startswith('_')})
    try:
        para_MAIN_PARA(state)
        para_PROCESS_ENTER_KEY(state)
        para_RETURN_TO_PREV_SCREEN(state)
        para_SEND_USRADD_SCREEN(state)
        para_RECEIVE_USRADD_SCREEN(state)
        para_POPULATE_HEADER_INFO(state)
        para_WRITE_USER_SEC_FILE(state)
        para_CLEAR_CURRENT_SCREEN(state)
        para_INITIALIZE_ALL_FIELDS(state)
    except _GobackSignal:
        pass
    except ZeroDivisionError:
        state['_abended'] = True
    _snap = dict.__getitem__(state, '_initial_snapshot')
    state['_state_diffs'] = {
        k: {'from': _snap[k], 'to': dict.__getitem__(state, k)}
        for k in _snap
        if _snap[k] != dict.get(state, k)
    }
    return state


if __name__ == '__main__':
    result = run()
    for line in result.get('_display', []):
        print(line)

